name: Process Specific YAML File in SAP Directory

on:
  workflow_dispatch:

jobs:
  process-yaml-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O yq
        chmod +x yq

    - name: Extract YAML attribute
      id: extract_yaml
      run: |
        # Extract the 'version' attribute from the YAML file
        version=$(./yq eval '.materials.media[0].url' SAP/SWPM20SP18_latest/SWPM20SP18_latest.yaml)
        echo "YAML url: $url"
        # Set the extracted value as an output for later use
        echo "::set-output name=url::$url"

    - name: Use the extracted version
      run: echo "The extracted version is ${{ steps.extract_yaml.outputs.version }}"
